language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly

matrix:
  allow_failures:
  - python: nightly

env:
  - SPHINX=>=1.3,<1.4dev
  - SPHINX=>=1.4,<1.5dev
  - SPHINX=>=1.5,<1.6dev
  - SPHINX=>=1.6,<1.7dev
  - SPHINX=>=1.7,<1.7dev
  - SPHINX=>=1.8,<1.9dev
  - SPHINX=

notifications:
    email: false
    irc:
      channels:
        - "irc.iiens.net#Clicky"
      on_success: change
      on_failure: always

branches:
  only:
    - master

install:
  - "pip install sphinx-testing" # required for tests
  - "pip install Sphinx$SPHINX"
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls check-manifest flake8; fi"

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8; fi"
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run --source=sphinxcontrib.varlinks `type -p nosetests`; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then nosetests; fi"
  - "popd"

after_success:
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi"
  - "popd"

